[package]
name = "sum_as_string_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "sum_as_string_rs"
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.10", features = ["lua51", "module"] }

[build-dependencies]
expose-shared-library = { path = "../..", features = ["lua"] }
